id: D05F317E2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:56:05+00:00'
last_modified: '2022-05-27T06:04:54.734163+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    17e0:
      image_group_id: I1PD95902
      title: རབ་ཏུ་བྱེད་པ་ལག་པའི་ཚད་ཀྱི་ཚིག་ལེའུར་བྱས་པ།
      total_pages: 1605
      order: 57
      base_file: 17e0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
