id: P2E6EB349
initial_creation_type: ocr
source_metadata:
  volumes:
    4f4c4397aa2d4c0aa0fed33b85a05c81:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: རབ་ཏུ་བྱེད་པ་ལག་པའི་ཚད་ཀྱི་ཚིག་ལེའུར་བྱས་པ།
      total_pages: 1605
      volume_number: 57
